# readthedocs configuration script
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: dirhtml
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt

formats: all
