# Action which validates the ability to build this extension against multiple
# versions of Sphinx using various Python interpreters.

name: Build

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/build.yml'
      - 'sphinxcontrib/**'
      - 'tests/**'
      - '.flake8'
      - '.pylintrc'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'requirements_dev.txt'
      - 'tox.ini'
  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/build.yml'
      - 'sphinxcontrib/**'
      - 'tests/**'
      - '.flake8'
      - '.pylintrc'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'requirements_dev.txt'
      - 'tox.ini'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx52, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx53, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx52, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx53, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx60, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx61, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx62, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx52, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx53, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx60, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx61, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx62, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx52, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx53, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx60, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx61, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx62, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.11", toxenv: py311-sphinx52, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.11", toxenv: py311-sphinx53, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.11", toxenv: py311-sphinx60, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.11", toxenv: py311-sphinx61, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.11", toxenv: py311-sphinx62, cache: ~/.cache/pip }
            - { os:   macos-latest, python: "3.11", toxenv: py311-sphinx62, cache: ~/Library/Caches/pip }
            - { os: windows-latest, python: "3.11", toxenv: py311-sphinx62, cache: ~\AppData\Local\pip\Cache }
            - { os:  ubuntu-latest, python: "3.11", toxenv:         flake8, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.11", toxenv:         pylint, cache: ~/.cache/pip }

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Cache pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ${{ matrix.cache }}
        key: ${{ matrix.os }}-${{ matrix.python }}-pip-

    - name: Install dependencies
      run: python -m pip install --upgrade tox

    - name: tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
