name: build

on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/build.yml'
      - 'sphinxcontrib/**'
      - 'tests/**'
      - 'requirements_dev.txt'
      - 'setup.cfg'
      - 'setup.py'
      - 'tox.ini'
  pull_request:
    branches:
    - master
    paths:
      - '.github/workflows/build.yml'
      - 'sphinxcontrib/**'
      - 'tests/**'
      - 'requirements_dev.txt'
      - 'setup.cfg'
      - 'setup.py'
      - 'tox.ini'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - { os:  ubuntu-latest, python:  "2.7", toxenv:  py27-sphinx18, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx18, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx40, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx41, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx42, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx43, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.7", toxenv:  py37-sphinx44, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx18, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx40, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx41, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx42, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx43, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.8", toxenv:  py38-sphinx44, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx18, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx40, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx41, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx42, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx43, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python:  "3.9", toxenv:  py39-sphinx44, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx18, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv: py310-sphinx44, cache: ~/.cache/pip }
            - { os:   macos-latest, python:  "2.7", toxenv:  py27-sphinx18, cache: ~/Library/Caches/pip }
            - { os:   macos-latest, python: "3.10", toxenv: py310-sphinx44, cache: ~/Library/Caches/pip }
            - { os: windows-latest, python:  "2.7", toxenv:  py27-sphinx18, cache: ~\AppData\Local\pip\Cache }
            - { os: windows-latest, python: "3.10", toxenv: py310-sphinx44, cache: ~\AppData\Local\pip\Cache }
            - { os:  ubuntu-latest, python: "3.10", toxenv:         flake8, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, python: "3.10", toxenv:         pylint, cache: ~/.cache/pip }

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Cache pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ${{ matrix.cache }}
        key: ${{ matrix.os }}-${{ matrix.python }}-pip-

    - name: Install dependencies
      run: python -m pip install --upgrade tox

    - name: tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
