# Provides a manual action allowing maintainers to trigger a validation
# run which will publish results to Confluence Cloud.
#
#  sphinxcontrib-confluencebuilder -- Development Space
#  https://sphinxcontrib-confluencebuilder.atlassian.net/wiki/spaces/DEVELOP

name: Confluence Publish Check

on:
  workflow_dispatch:
    inputs:
      python:
        description: 'Python interpreter'
        required: true
        default: '3.12'
      space:
        description: 'Space'
        default: 'DEVELOP'
      test_key:
        description: 'Test Key (Base Page)'
        default: 'test-holder'
      test_desc:
        description: 'Test Description'
        default: 'test state'
      test_version:
        description: 'Test Version'
        default: 'main'

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    container: ghcr.io/sphinx-contrib/confluencebuilder/doctest:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ github.event.inputs.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ github.event.inputs.python }}

    - name: tox
      env:
        CONFLUENCE_AUTH: ${{ secrets.CONFLUENCE_AUTH }}
        CONFLUENCE_SPACE: ${{ github.event.inputs.space }}
        CONFLUENCE_TEST_DESC: ${{ github.event.inputs.test_desc }}
        CONFLUENCE_TEST_KEY: ${{ github.event.inputs.test_key }}
        CONFLUENCE_TEST_VERSION: ${{ github.event.inputs.test_version }}
      run: tox -e validation
