# Action which validates the ability to build this extension's documentation.

name: Documentation

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/docs.yml'
      - 'doc/**'
      - 'CHANGES.rst'
  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/docs.yml'
      - 'doc/**'
      - 'CHANGES.rst'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/sphinx-contrib/confluencebuilder/doctest:main

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -e .

    - name: HTML
      run: |
        . venv/bin/activate
        cd doc
        make html

    - name: PDF
      run: |
        . venv/bin/activate
        cd doc
        make latexpdf

    - name: Archive generated PDF
      uses: actions/upload-artifact@v4
      with:
        name: sphinxcontrib-confluencebuilder.pdf
        path: doc/_build/latex/sphinxconfluencebuilder.pdf
        retention-days: 10

    - name: Archive PDF Raw Output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pdf-output
        path: |
          doc/_build/latex/sphinxconfluencebuilder.log
          doc/_build/latex/sphinxconfluencebuilder.tex
        retention-days: 1
