# Provides a manual action allowing developers to trigger a tox run
# against a specific version of Sphinx directly from Sphinx's official
# repository. This action can be used by this extension's maintainers
# as well as sphinx-contrib owners (if needed).

name: Sphinx Development Check

on:
  workflow_dispatch:
    inputs:
      python:
        description: 'Python interpreter'
        required: true
        default: '3.11'
      sphinx:
        description: 'Sphinx Revision'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ github.event.inputs.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ github.event.inputs.python }}

    - name: Cache pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ubuntu-latest-${{ github.event.inputs.python }}-pip-

    - name: Install dependencies
      run: python -m pip install --upgrade tox

    - name: tox
      env:
        SPHINX_VER: ${{ github.event.inputs.sphinx }}
      run: tox -e develop
