# Provides a manual action allowing maintainers to trigger a validation
# run which will publish results to Confluence Cloud.
#
#  sphinxcontrib-confluencebuilder -- Development Space
#  https://sphinxcontrib-confluencebuilder.atlassian.net/wiki/spaces/DEVELOP

name: Publish Check

on:
  workflow_dispatch:
    inputs:
      python:
        description: 'Python interpreter'
        required: true
        default: '3.9'
      space:
        description: 'Space'
        default: 'DEVELOP'
      test_key:
        description: 'Test Key (Base Page)'
        default: 'test-holder'
      test_desc:
        description: 'Test Description'
        default: 'test state'
      test_version:
        description: 'Test Version'
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ github.event.inputs.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ github.event.inputs.python }}

    - name: Cache pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ubuntu-latest-${{ github.event.inputs.python }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get install \
            dvipng \
            graphviz \
            texlive-latex-extra \
            texlive-latex-recommended \
            -y
        python -m pip install --upgrade tox

    - name: tox
      env:
        CONFLUENCE_AUTH: ${{ secrets.CONFLUENCE_AUTH }}
        CONFLUENCE_SPACE: ${{ github.event.inputs.space }}
        CONFLUENCE_TEST_DESC: ${{ github.event.inputs.test_desc }}
        CONFLUENCE_TEST_KEY: ${{ github.event.inputs.test_key }}
        CONFLUENCE_TEST_VERSION: ${{ github.event.inputs.test_version }}
      run: tox -e validation
